### ISSUE TITLE
Clarification regarding interface

### ISSUE THREAD

**Issue by travisbrady** [DataResponsibly/ShaRP#45]
### Ask your question here.

First, thank you for ShaRP! This is such an awesome idea and I'm very glad to see the code available on github and easily installable with pip.

I have a question about the interface of .fit lacking a `y` argument. How does ShaRP understand what the ranks are if they aren't provided in the [plot_basic_usage.py](https://github.com/DataResponsibly/ShaRP/blob/main/examples/plot_basic_usage.py#L35) script? Is it implicit just based on the order of the data?
 
Also that script creates a variable called `rank` but then it isn't used in the context of the ShaRP object, could it also have been passed into .fit like the y parameter?

thank you again

**Comment by joaopfonseca** [comment]
Hi Travis, thank you for reaching out! I'm glad you find it useful.

We don't pass a `y` in `ShaRP` since the feature contributions are based on shapley values; this means that to find these contributions, we're going to apply perturbations to a given observation we are interested in explaining (this is the tl;dr, we have a more thorough explanation on our [ArXiv paper](https://arxiv.org/abs/2401.16744), and an even better explanation in a new version of this paper we're going to upload in the next few days/weeks). During this process, we need to compute the ranking, score or whatever other metric (which we refer to as quantity of interest, and depends on the problem you're tackling) to find out the impact of a certain perturbation. Because of this, we need to pass the function that will output target we want to explain. In the [basic usage](https://dataresponsibly.github.io/ShaRP/auto_examples/plot_basic_usage.html#sphx-glr-auto-examples-plot-basic-usage-py) example, we pass the parameter `target_function` to do this.

In that example, we're explaining the model's decisions over a set of observations we want to analyze. To answer your last question, you shouldn't pass it to the `fit` parameter (unless you're referring to training a classifier/ranker, which would be a different case), the `fit` is just used to feed a "reference" dataset for ranking. Regarding the `rank` variable not being used, that's correct, in that example we only use it to set up the last visualization (to produce the waterfall chart).

Hope this helps! I'm going to close the issue, but feel free to reopen it if you have any follow up questions.
